force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Aditional_Skills__c.field-meta.xml
<CustomField>
    <fullName>Aditional_Skills__c</fullName>
    <label>Aditional Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup field referencing the client or company that is hiring for the position.</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected client should have the Status as Active</errorMessage>
        <filterItems>
            <field>Client__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <description>Specifies the nature of employment: Full-Time, Part-Time, Contract, Internship, etc.</description>
    <inlineHelpText>Specify the nature of the employment for this role</inlineHelpText>
    <label>Employment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Time</fullName>
            </value>
            <value>
                <fullName>Part-Time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Experience_Required__c.field-meta.xml
<CustomField>
    <fullName>Experience_Required__c</fullName>
    <description>Total Experience Required for the job position.</description>
    <label>Experience Required</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <description>The mode of the hiring process (e.g., Online, In-Person, Telephonic, Video Call).</description>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>College Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Shift_Time__c.field-meta.xml
<CustomField>
    <fullName>Shift_Time__c</fullName>
    <description>Will show the shift timings.</description>
    <label>Shift Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Night</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <description>A multi-select list of technical or functional skills required for the position.</description>
    <inlineHelpText>Enter comma-separated skills. For example: Apex Programming, Admin, LWC, etc.</inlineHelpText>
    <label>Skills Required</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Soft_skills__c.field-meta.xml
<CustomField>
    <fullName>Soft_skills__c</fullName>
    <label>Soft skills</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Work_Mode__c.field-meta.xml
<CustomField>
    <fullName>Work_Mode__c</fullName>
    <description>This field stores the job location.</description>
    <inlineHelpText>General location of the job.</inlineHelpText>
    <label>Work Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Off Site</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Client object, linking the project to the company it is being executed for.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LinkedInService_Test.cls
/**
 * @description
 * Test class for LinkedInService.
 * Covers success scenarios, job detail retrieval,
 * company name fetch, LinkedIn post creation,
 * and callout exception handling.
 *
 * @author AJAY Kaurav
 * @since 2025-11-25
 */

@IsTest
public class LinkedInService_Test {

    @TestSetup
    static void setupTestData() {

         Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

     User u = new User(
        Alias = 'tuser',
        Email = 'testuser@test.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'User',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'Asia/Kolkata',
        Username = 'testuser' + System.currentTimeMillis() + '@test.com'
    );
    insert u;

        Client__c client = Recruitment_TestDataFactory.createClient('Test Client', 'client@test.com');
        insert client;

        Project__c proj = Recruitment_TestDataFactory.createProject('Test Project');
        insert proj;

        Job_Position__c jobPos = Recruitment_TestDataFactory.createJobPosition(client, proj);
        jobPos.Skills_Required__c = 'Apex, LWC, Integration';
        jobPos.Employment_Type__c = 'Full-Time';
        jobPos.Mode__c = 'Online';
        jobPos.Work_Mode__c = 'Hybrid';
        jobPos.Shift_Time__c = 'Day';
        jobPos.Qualification__c = 'B.Tech';
        jobPos.Experience_Required__c = 2;
        jobPos.Soft_skills__c = 'Communication';
        jobPos.Aditional_Skills__c = 'Git';
        insert jobPos;
    }

    // ----------------------------------------------------
    // SUCCESS: Get Job Details
    // ----------------------------------------------------
    @IsTest
    static void testGetJobDetailsForLinkedinSuccess() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Job_Position__c jp = [SELECT Id FROM Job_Position__c LIMIT 1];
        
        System.runAs(u) {
        Test.startTest();
        Job_Position__c result = LinkedInService.getJobDetailsForLinkedin(jp.Id);
        Test.stopTest();

        System.assertNotEquals( null, result, 'Job details should not be null');
        System.assertEquals('Full-Time', result.Employment_Type__c, 'Employment type should be Full-Time');
        }

    }

    // ----------------------------------------------------
    // SUCCESS: Get Company Name
    // ----------------------------------------------------
    @IsTest
    static void testGetCompanyNameSuccess() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();
        String cname = LinkedInService.getCompanyName();
        Test.stopTest();

        System.assertNotEquals('',cname, 'Company name should not be empty');
        System.assertNotEquals(null, cname, 'Company name should not be null');
        }

    }

/**
 * @description
 * Mock implementation for successful LinkedIn post callout.
 */
    private class LinkedInMockSuccess implements HttpCalloutMock {
/**
 * @description
 * Returns a mocked successful HTTP response
 * for LinkedIn post creation callout.
 *
 * @param req Incoming HTTP request
 * @return Mocked HTTP response with success status
 */
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(201);
            res.setBody('{"id":"urn:li:ugcPost:98765"}');
            return res;
        }
    }

    @IsTest
    static void testCreatePostSuccess() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new LinkedInMockSuccess());

    System.runAs(u) {
        Test.startTest();
        String res = LinkedInService.createPost('Test Hiring Post');
        Test.stopTest();

        System.assert(
            res.contains('urn:li:ugcPost'),
            'Response should contain LinkedIn post URN'
        );
    }
    }

/**
 * @description
 * Mock implementation for failed LinkedIn post callout.
 */
    private class LinkedInMockError implements HttpCalloutMock {
/**
 * @description
 * Simulates a callout exception for LinkedIn
 * post creation failure scenario.
 *
 * @param req Incoming HTTP request
 * @return Never returns a response (throws exception)
 */
        public HttpResponse respond(HttpRequest req) {
            throw new CalloutException('Mocked LinkedIn failure!');
        }
    }

    @IsTest
    static void testCreatePostCalloutException() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new LinkedInMockError());
        Boolean exceptionThrown = false;

        System.runAs(u) {
        try {
            Test.startTest();
            LinkedInService.createPost('Error Post');
            Test.stopTest();
        } catch (Exception ex) {
            exceptionThrown = true;
        }

        System.assertEquals(true, exceptionThrown, 'Exception must be thrown on callout failure');
    }
}
}