force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <description>This field store&apos;s current location of the candidate.</description>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <description>This field stores date of birth of the candidate.</description>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field stores email of candidate.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Highest_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Highest_Qualification__c</fullName>
    <inlineHelpText>Give comma separated values eg: B.Tech, M.Sc, M.Com, M.A, MBA</inlineHelpText>
    <label>Highest Qualification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/IsBillable__c.field-meta.xml
<CustomField>
    <fullName>IsBillable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field shows whether the candidate is billable(on project) or not.</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Please enter valid phone number with availability of whatsapp.</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Total_Experience__c.field-meta.xml
<CustomField>
    <fullName>Total_Experience__c</fullName>
    <description>Total number of years of professional experience the candidate has across all previous roles</description>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A free-text field where recruiters can enter additional notes or background information about the client — such as their hiring preferences, company culture, or special instructions.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Store&apos;s Primary Email Of Cient</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Stores The Primary Phone Details Of The Client</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Recruiter__c.field-meta.xml
<CustomField>
    <fullName>Recruiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The internal team member (recruiter) assigned to manage the relationship with this client or handle job requisitions from this company. This is typically a lookup field to the User object.</description>
    <label>Recruiter</label>
    <referenceTo>Recruiter__c</referenceTo>
    <relationshipName>Client_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the candidate being interviewed. Used to associate the interview with a specific candidate profile.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief overview of the job responsibilities and expectations.</description>
    <label>Description</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field stores Email of client person.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field stores Client&apos;s Phone number.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Recruiter__c.field-meta.xml
<CustomField>
    <fullName>Recruiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal recruiter or staff responsible for filling the position. Typically a lookup to User.</description>
    <label>Recruiter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will show that project is currently Active or not.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Actual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost__c</fullName>
    <description>The actual monetary expenditure incurred on the project to date.</description>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>The financial budget allocated for the entire project (typically in currency format).</description>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief summary of the project&apos;s scope, objectives, and business purpose.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The planned or actual completion date of the project.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_employees__c.field-meta.xml
<CustomField>
    <fullName>No_of_employees__c</fullName>
    <description>The number of employees or resources assigned or planned for this project.</description>
    <inlineHelpText>Number of employees working on this project</inlineHelpText>
    <label>No of employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The planned or actual start date of the project.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recruiter__c/Recruiter__c.object-meta.xml
<CustomObject>
    <label>Recruiter</label>
    <nameField>
        <label>Recruiter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruiters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recruiter__c/fields/Alternate_number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_number__c</fullName>
    <description>Optional backup contact number for the recruiter, such as a personal or secondary work phone.</description>
    <label>Alternate number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Recruiter__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The recruiter&apos;s primary work email address. Used for notifications, communication, and system integration.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Recruiter__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary contact number of the recruiter. Used for direct communication and internal reference.</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>WorkOrderID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the onboarded candidate.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The expected or actual end date of the candidate on the project.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the project they’re assigned to.</description>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Recruiter__c.field-meta.xml
<CustomField>
    <fullName>Recruiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the recruiter.</description>
    <label>Recruiter</label>
    <referenceTo>Recruiter__c</referenceTo>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Role_on_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Project__c</fullName>
    <description>Role played by the candidate (e.g., Developer, Analyst, Tester).</description>
    <label>Role on Project</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The date the candidate joined or started on the project.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Recruitment_TestDataFactory.cls
/*
##################################################### 
# Created By (Date)   : Admin (22 Jul, 2025)
# Description         : This is a Data Factory class for test classes.
# Modifications Log   : 
* Ver    Date              Author         Modification
* 1.0    22 Jul, 2025      Admin          Initial Version
#####################################################
*/

@isTest
public class Recruitment_TestDataFactory {
    
/**
* @description  : Return a Candidate__c record with Name and Email.
* @param name   - Candidate name
* @param email  - Candidate email
* @return Candidate__c instance (not inserted)
*/
    public static Candidate__c createCandidate(String name, String email) {
        return new Candidate__c(
            Last_name__c = name,
            Email__c = email,
            Date_of_Birth__c = Date.newInstance(1990, 1, 1),
            Phone__c = '1234567890',
            Current_Location__c = 'New York',
            Total_Experience__c = 5,
            Highest_Qualification__c = 'B.Tech',
            IsBillable__c=true
        );
    }
    
/**
* @description  : Return a Project__c record with Description.
* @param description - Project description
* @return Project__c instance (not inserted)
*/
    public static Project__c createProject(String description) {
        return new Project__c(
            Description__c = description,
            No_of_employees__c = 10,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(30),
            Budget__c = 50000,
            Actual_Cost__c = 20000,
            Active__c = true
        );
    }
    
/**
* @description  : Return a Recruiter__c record with Name and Email.
* @param name   - Recruiter name
* @param email  - Recruiter email
* @return Recruiter__c instance (not inserted)
*/
    public static Recruiter__c createRecruiter(String lastName, String email) {
        return new Recruiter__c(
            Name = lastName,
            Email__c = email,
            Phone__c = '9876543210',
            Alternate_number__c = '8765432109'
        );
    }
    
/**
* @description  : Return a Work_Order__c record with related Candidate, Project, and Recruiter.
* @param Id   - candidate Id
* @param Id   - project Id
* @param Id   - recruiter Id
* @return Work_Order__c instance (not inserted)
*/
    
    public static Work_Order__c createWorkOrder(Id candidateId, Id projectId, Id recruiterId) {
        return new Work_Order__c(
            Candidate__c = candidateId,
            Project__c = projectId,
            Role_on_Project__c = 'Developer', 
            Recruiter__c = recruiterId,
            Renewed__c = false,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addMonths(6),
            Status__c = 'Working', 
            Salary_Offered__c = 50000
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return a Client__c record with sample data.
* @param name: Name for Client.
* @param email: Email for Client.
* @return Client__c instance (not inserted).
*/
    public static Client__c createClient(String name, String email) {
        return new Client__c(
            Name = name,
            Phone__c = '9999999999',
            Email__c = email,
            isActive__c = true
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return a Job_Position__c record with sample data.
* @param client   - Related Client__c record (required).
* @param Project  - Related Project__c record (required).
* @return Job_Position__c instance (not inserted).
*/
    public static Job_Position__c createJobPosition(Client__c client, Project__c proj) {
        return new Job_Position__c(
            Job_Title__c = 'Salesforce Developer',
            Client__c = client.Id,
            Employment_Type__c = 'Full-Time',
            Skills_Required__c = 'Salesforce Developer',
            Project__c = proj.Id
       
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Interview__c record with sample data.
* @param candidate - Related Candidate__c record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Interview__c instance (not inserted).
*/
    public static Interview__c createInterview(Candidate__c candidate, Job_Position__c jobPos) {
        return new Interview__c(
            Candidate__c = candidate.Id,
            Job_Position__c = jobPos.Id,                   
            Interview_Status__c = 'New',
            Feedback__c = 'Initial feedback'
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Interview__c record with sample data.
* @param candidate - Related Candidate__c record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Interview__c instance (not inserted).
*/
    public static Interview__c createInterviewWithoutRound(Candidate__c candidate, Job_Position__c jobPos) {
        return new Interview__c(
            Candidate__c = candidate.Id,
            Job_Position__c = jobPos.Id,                    
            Interview_Status__c = 'New',
            Feedback__c = 'Initial feedback'
        );
    }

/** 
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Client__c record with sample data.
* @param candidate - Related Candidate__c record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Client__c instance.
*/
    public static Client__c createFlexClient(String name, String email) {
        return new Client__c(
            Name = name,
            Phone__c = '9999999999',
            Email__c = email,
            isActive__c = true
        );
    }
 
/* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Job_Position__c record with sample data.
* @return Job_Position__c instance.
*/     
    public static Job_Position__c createFlexJobPosition() {
        return new Job_Position__c(
            Job_Title__c = 'Salesforce Developer',        
            Employment_Type__c = 'Full-Time',
            Skills_Required__c = 'Salesforce, Admin',       
            Status__c = 'Open'          
        );
    }
      public static CustomSetting__c getValidationBypassSetting() {
        CustomSetting__c cs = CustomSetting__c.getOrgDefaults();
        if (cs == null) {
            cs = new CustomSetting__c(
                SetupOwnerId = UserInfo.getOrganizationId()
            );
        }
        return cs;
    }
    
    
     /**
     * @author (date): Admin (9 september, 2025)
     * @description  : Returns an Event record with sample data related to the given Candidate__c.
     * @param candidate - Related Candidate__c record (required).
     * @return Event instance.
     */
    
    public static Event createEvent(Candidate__c candidate,Job_Position__c job) {
        return new Event(
            Subject = 'Team Meeting',
            StartDateTime = System.now().addDays(1),
            EndDateTime = System.now().addDays(1).addHours(1),
            	WhatId=job.id,
          
            DurationInMinutes = 60,
          	Candidate__c=candidate.Id,
            Location = 'Conference Room',
            Description = 'Discussion about project status'
        );
    }
}