force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field stores email of candidate.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Leave_Notify_Config__mdt/Leave_Notify_Config__mdt.object-meta.xml
<CustomObject>
    <label>Leave Notify Configuration</label>
    <pluralLabel>Leave Notify Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/LeaveRequestController.cls
public without sharing class LeaveRequestController {

    @AuraEnabled
    public static void createTimesheets(String payloadJson) {

        TimesheetContext ctx =
            LeaveRequestContextBuilder.build(payloadJson);

        LeaveRequestProcessor.process(ctx);

        LeaveRequestDmlService.persist(ctx);

        LeaveRequestEmailService.notifyIfRequired(ctx);
    }
    @AuraEnabled(cacheable=true)
    public static List<Leave_Notify_Config__mdt> getNotifyConfigs() {
        return [
            SELECT Name__c, Email__c
            FROM Leave_Notify_Config__mdt
            WHERE Is_Active__c = true
            WITH USER_MODE
        ];
    }
    @AuraEnabled
    public static Id getLoggedInCandidateId() {

        User u = [
            SELECT ContactId
            FROM User
            WHERE Id = :UserInfo.getUserId()
            WITH USER_MODE
            LIMIT 1
        ];

        if (u.ContactId == null) {
            return null;
        }

        List<Candidate__c> c = [
            SELECT Id
            FROM Candidate__c
            WHERE Contact__c = :u.ContactId
            WITH USER_MODE
            LIMIT 1
        ];

        return c.isEmpty() ? null : c[0].Id;
    }
}