force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field stores email of candidate.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Store&apos;s Primary Email Of Cient</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the candidate being interviewed. Used to associate the interview with a specific candidate profile.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>The scheduled or completed date and time of the interview. Important for planning and status tracking.</description>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Mode__c.field-meta.xml
<CustomField>
    <fullName>Interview_Mode__c</fullName>
    <description>The format or medium of the interview.</description>
    <label>Interview Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephonic</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the open position or job role the interview is for. Helps identify the context of the interview.</description>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup field referencing the client or company that is hiring for the position.</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected client should have the Status as Active</errorMessage>
        <filterItems>
            <field>Client__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field stores Email of client person.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This field stores title of the job position.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <description>A multi-select list of technical or functional skills required for the position.</description>
    <inlineHelpText>Enter comma-separated skills. For example: Apex Programming, Admin, LWC, etc.</inlineHelpText>
    <label>Skills Required</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Client object, linking the project to the company it is being executed for.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendJobPositionToCandidateContr_Test.cls
@IsTest
public class SendJobPositionToCandidateContr_Test {

    @TestSetup
    static void setupData() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User u = new User(
            FirstName = 'Test',
            LastName = 'Owner',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser' + System.currentTimeMillis() + '@example.com',
            CommunityNickname = 'testuser' + System.currentTimeMillis(),
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_IN',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;

       
        Client__c client = Recruitment_TestDataFactory.createClient('Test Client', 'client@example.com');
        Project__c project = Recruitment_TestDataFactory.createProject('Test Project');

        Candidate__c cand = Recruitment_TestDataFactory.createCandidate('Test Candidate', 'candidate6@example.com');
        Candidate__c cand1 = Recruitment_TestDataFactory.createCandidate('Test Candidate1', 'candidate7@example.com');
        Candidate__c cand2 = Recruitment_TestDataFactory.createCandidate('Test Candidate2', 'candidate8@example.com');

        insert new List<SObject>{ client, project, cand, cand1, cand2 };

       
        Job_Position__c job = Recruitment_TestDataFactory.createJobPosition(client, project);
        job.Client__c = client.Id;
        job.Job_Title__c = 'Salesforce Developer';
        job.Skills_Required__c = 'Apex; Java';
        insert job;

        
        Interview__c inter = Recruitment_TestDataFactory.createInterview(cand, job);
        inter.Interview_Date__c = DateTime.now().addDays(1);
        inter.Interview_Mode__c = 'Online';
        insert inter;
    }

    @IsTest
    static void testGetJobAndCandidatesSuccess()
{
        // Fetch setup data
          User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Job_Position__c job = [SELECT Id FROM Job_Position__c LIMIT 1];
        Interview__c inter = [SELECT Id FROM Interview__c LIMIT 1];
         System.runAs(u) {
        Test.startTest();
        Map<String, Object> result = SendJobPositionToCandidateController.getJobAndCandidates(job.Id, new List<Id>{inter.Id});
        Test.stopTest();

        System.assertNotEquals(null, result, 'Response should not be null');
        System.assert(result.containsKey('jobPosition'), 'Job data should be present');
        System.assert(result.containsKey('candidates'), 'Candidate list should be present');

        Job_Position__c fetchedJob = (Job_Position__c) result.get('jobPosition');
        List<Candidate__c> fetchedCandidates = (List<Candidate__c>) result.get('candidates');

        System.assertEquals('Salesforce Developer', fetchedJob.Job_Title__c, 'Job Title mismatch');
        System.assertEquals(1, fetchedCandidates.size(), 'Should return only one candidate linked to interview');
        System.assertEquals('candidate6@example.com', fetchedCandidates[0].Email__c, 'Email mismatch');
    }
}

    /*@isTest
    static void test_NoInterviewIds() {
        Job_Position__c job = [SELECT Id FROM Job_Position__c LIMIT 1];

        Test.startTest();
        Map<String, Object> result = SendJobPositionToCandidateController.getJobAndCandidates(job.Id, new List<Id>());
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals(true, result.containsKey('jobPosition'));
        System.assertEquals(true, result.containsKey('candidates'));
        System.assertEquals(0, ((List<Candidate__c>)result.get('candidates')).size(), 'No interviews → no candidates');
    }

    @isTest
    static void test_JobId_Null() {
        Test.startTest();
        Map<String, Object> result = SendJobPositionToCandidateController.getJobAndCandidates(null, new List<Id>());
        Test.stopTest();

        System.assertEquals(0, result.size(), 'Null job id should return empty map');
    }*/
}