force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the candidate being interviewed. Used to associate the interview with a specific candidate profile.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Status__c.field-meta.xml
<CustomField>
    <fullName>Interview_Status__c</fullName>
    <description>Final result of the interview round.</description>
    <label>Interview Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Recruiter Screening</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the open position or job role the interview is for. Helps identify the context of the interview.</description>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Experience_Required__c.field-meta.xml
<CustomField>
    <fullName>Experience_Required__c</fullName>
    <description>Total Experience Required for the job position.</description>
    <label>Experience Required</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This field stores title of the job position.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the current stage of the job (e.g., Draft, Open,  Closed).</description>
    <inlineHelpText>Indicates the current status of the job position.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Total_Openings__c.field-meta.xml
<CustomField>
    <fullName>Total_Openings__c</fullName>
    <description>The number of candidates the client is looking to hire for this position.</description>
    <label>Total Openings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JobPositionController.cls
/**
* @File Name : JobPositionController.cls
* @Description : Controller for the Child Component of Candidate Card joppositionCard
* @Author :
* @Last Modified By :
* @Last Modified On : August 19, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | August 19, 2025 |   | Initial Version
**/
public with sharing class JobPositionController {
    @AuraEnabled(cacheable=true)
    public static List<Job_Position__c> getOpenJobPositions(String searchKey) {
    String key = '%' + searchKey + '%';

    return [
        SELECT Id, Name, Job_Title__c, Status__c, Total_Openings__c, Experience_Required__c, CreatedDate
        FROM Job_Position__c
        WHERE Status__c = 'Open'
        AND (
            Name LIKE :key
            OR Job_Title__c LIKE :key
        )
        ORDER BY CreatedDate DESC
    ];
}

// no record found message

 
    @AuraEnabled
    public static void assignCandidatesToJobs(List<Id> candidateIds, List<Id> jobPositionIds) {
        List<Interview__c> interviews = new List<Interview__c>();

        for (Id jobId : jobPositionIds) {
            for (Id candidateId : candidateIds) {
                interviews.add(new Interview__c(
                    Candidate__c = candidateId,
                    Job_Position__c = jobId,
                    Interview_Status__c = 'New'
                ));
            }
        }

        if (!interviews.isEmpty()) {
            insert interviews;
        }
    }

}