force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <description>This object save records of daily work entries.</description>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Daily_Task__c.field-meta.xml
<CustomField>
    <fullName>Daily_Task__c</fullName>
    <label>Daily Task</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Represents the working date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Manager_Approved__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Reason_for_Leave__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leave__c</fullName>
    <label>Reason for Leave</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Day Leave</fullName>
            </value>
            <value>
                <fullName>Half Day - SH</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Half Day - FH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeaveRequestTimesheetFactory.cls
public class LeaveRequestTimesheetFactory {

    public static Timesheet__c build(
        TimesheetContext ctx,
        Date d
    ) {
        Datetime dt = Datetime.newInstance(d, Time.newInstance(0,0,0,0));

        return new Timesheet__c(
            Name =
                ctx.candidate.Name + '-' +
                ctx.input.leaveDuration + '-' +
                dt.format('EEE') + ', ' +
                dt.format('dd MMM'),
            Candidate__c = ctx.input.candidateId,
            Date__c = d,
            Status__c = ctx.input.leaveDuration,
            Reason_for_Leave__c = ctx.input.reason,
            Daily_Task__c = 'Leave',
            Manager_Approved__c = false
        );
    }
}