force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Please enter valid phone number with availability of whatsapp.</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Stores The Primary Phone Details Of The Client</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>New Lead</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the candidate being interviewed. Used to associate the interview with a specific candidate profile.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <description>Interviewer&apos;s comments or evaluation notes. Provides qualitative insight for decision making.</description>
    <label>Feedback</label>
    <length>12000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>The scheduled or completed date and time of the interview. Important for planning and status tracking.</description>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Mode__c.field-meta.xml
<CustomField>
    <fullName>Interview_Mode__c</fullName>
    <description>The format or medium of the interview.</description>
    <label>Interview Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephonic</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Status__c.field-meta.xml
<CustomField>
    <fullName>Interview_Status__c</fullName>
    <description>Final result of the interview round.</description>
    <label>Interview Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Recruiter Screening</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the open position or job role the interview is for. Helps identify the context of the interview.</description>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>The stage or round of the interview process. Helps track candidate progress.</description>
    <label>Round</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interview_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Managerial</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup field referencing the client or company that is hiring for the position.</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected client should have the Status as Active</errorMessage>
        <filterItems>
            <field>Client__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This field stores title of the job position.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field stores Client&apos;s Phone number.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the current stage of the job (e.g., Draft, Open,  Closed).</description>
    <inlineHelpText>Indicates the current status of the job position.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Client object, linking the project to the company it is being executed for.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>WorkOrderID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the onboarded candidate.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the project they’re assigned to.</description>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Role_on_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Project__c</fullName>
    <description>Role played by the candidate (e.g., Developer, Analyst, Tester).</description>
    <label>Role on Project</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Assignment status: Assigned, On Hold, Released, Completed, etc.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Extended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Onhold</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterviewTriggerHelperTest.cls
/*
############################################################################   
# Created By (Date)   : Admin (26 Aug, 2025)
# Description         : Test class to verify InterviewTriggerHelper logic.
# Modifications Log   : 
* Ver    Date              Author         Modification
* 1.0    26 Aug, 2025      Admin          Updated for revised helper methods
#############################################################################
*/

@IsTest
public class InterviewTriggerHelperTest {    
    
    @testSetup
    static void setupData() {
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        // Insert test user
        User u = new User(
            FirstName = 'Test',
            LastName = 'Owner',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser' + System.currentTimeMillis() + '@example.com',
            CommunityNickname = 'testuser' + System.currentTimeMillis(),
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_IN',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        
        
        Client__c client = Recruitment_TestDataFactory.createClient('Test Client', 'client@example.com');
        Project__c project = Recruitment_TestDataFactory.createProject('Test Project');
        Candidate__c cand = Recruitment_TestDataFactory.createCandidate('Test Candidate', 'candidate@example.com');
        Candidate__c cand1 = Recruitment_TestDataFactory.createCandidate('Test Candidate1', 'candidate2@example.com');
        Candidate__c cand2 = Recruitment_TestDataFactory.createCandidate('Test Candidate2', 'candidate1@example.com');
        insert new List<SObject>{ client, project, cand,cand1,cand2 };
            
            
            
            
            Job_Position__c job = Recruitment_TestDataFactory.createJobPosition(client, project);
        job.Client__c = client.Id; 
        insert job;
        
        //  Event ev=Recruitment_TestDataFactory.createEvent('a03dM000014Fc5NQAS',job);
        //insert ev;
        Interview__c inter = Recruitment_TestDataFactory.createInterview(cand, job);
        inter.Interview_Date__c = DateTime.now().addDays(1);  
        inter.Interview_Mode__c = 'Online';                     
        insert inter;
        
        
        Interview__c todayInterview = Recruitment_TestDataFactory.createInterview(cand1, job);
        todayInterview.OwnerId = u.Id;
        todayInterview.Interview_Date__c = System.now().addDays(1);
        insert todayInterview;
        System.debug('todayInterview'+todayInterview);
        
        Interview__c oldInterview = Recruitment_TestDataFactory.createInterview(cand2, job);
        oldInterview.OwnerId = u.Id;
        insert oldInterview;
        Test.setCreatedDate(oldInterview.Id, System.now().addMonths(-4));
        
        System.debug('todayInterview: ' + todayInterview);
        System.debug('oldInterview: ' + oldInterview);
        
      
        
        
        
        
        
        
        
        
        
        
        
    }
   
    
    
    
    /*
* @description : test HandleStatusChange Method : Ensures chatter post is NOT created if status or round is unchanged.
*/
    @IsTest
    static void testHandleStatusChange_NoChange_NoPost() {
        Interview__c interview = [
            SELECT Id, Candidate__c, Feedback__c, Round__c, Interview_Status__c 
            FROM Interview__c LIMIT 1
        ];
        
        Test.startTest();
        interview.Feedback__c = 'Test Feedback No Change';
        update interview;
        Test.stopTest();
        
        List<FeedItem> posts = [
            SELECT Id
            FROM FeedItem
            WHERE ParentId = :interview.Candidate__c
        ];
        System.assertEquals(0, posts.size(), 'No chatter post should be created if status and round are unchanged.');
    }
    
    /*
* @description : test HandleStatusChange Method : Ensures chatter post is created when status changes and feedback is provided.
*/
    @IsTest
    static void testHandleStatusChange_ChangeStatus() {
        Interview__c interview = [
            SELECT Id, Candidate__c, Round__c, Interview_Status__c 
            FROM Interview__c LIMIT 1
        ];
        
        Test.startTest();
        interview.Interview_Status__c = RecruitmentApp_Constants.INTERVIEW_STATUS_INTERVIEWING;
        interview.Feedback__c = 'Candidate showed good communication skills.';
        update interview;
        Test.stopTest();
        
        List<FeedItem> posts = [
            SELECT Id, Body, ParentId
            FROM FeedItem
            WHERE ParentId = :interview.Candidate__c
        ];
        System.assertEquals(1, posts.size(), 'Chatter post should be created when status changes.');
        System.assert(posts[0].Body.contains('Feedback:'), 'Chatter body should include Feedback text.');
    }
    
    /*
* @description : test HandleStatusChange Method :Ensures "Chatter post" are created when no interview-"round" value is provided.
*/
    @IsTest
    static void testHandleStatusChange_roundvaluenull() { 
        Job_Position__c jobpos = [
            SELECT Id
            FROM Job_Position__c
            LIMIT 1
        ]; 
        System.debug('jobpos'+jobpos);
        Candidate__c newcand = Recruitment_TestDataFactory.createCandidate('NewTestCandidate', 'NewTestCandidate@example.com');
        newcand.Phone__c = '9234567891';
        insert newcand;
        System.debug('newcand'+newcand);
        Interview__c rec = Recruitment_TestDataFactory.createInterviewWithoutRound(newcand, jobpos);
        insert rec;
        
        Test.startTest();
        rec.Interview_Status__c = RecruitmentApp_Constants.INTERVIEW_STATUS_INTERVIEWING;
        rec.Feedback__c = 'Candidate showed good communication skills.';
        update rec;
        Test.stopTest();
        
        List<FeedItem> posts = [
            SELECT Id, Body, ParentId
            FROM FeedItem
            WHERE ParentId = :rec.Candidate__c
        ];
        System.assertEquals(1, posts.size(), 'Chatter post should be created when status changes.');
        System.assert(posts[0].Body.contains('Feedback:'), 'Chatter body should include Feedback text.');
    }
    
    /*
* @description : test HandleStatusChange Method :Ensures no Work Order is created when feedback is exceeding feed character limit.
*/
    @isTest
    private static void testhandleStatusChange_BodyTooLong() {
        Interview__c interview = [
            SELECT Id, Candidate__c, Job_Position__r.Project__c, Job_Position__r.Job_Title__c
            FROM Interview__c LIMIT 1
        ];
        String largeFeedback = String.valueOf('X').repeat(11000);
        
        Test.startTest();
        interview.Interview_Status__c = RecruitmentApp_Constants.INTERVIEW_STATUS_OFFERED;
        interview.Feedback__c = largeFeedback;
        update interview;     
        Test.stopTest();
        
        List<FeedItem> posts = [
            SELECT Id
            FROM FeedItem
            WHERE ParentId = :interview.Candidate__c
        ];
        System.assertEquals(0, posts.size(), 'Chatter post should fail due to body length');
    }
    
    /*
* @description : test CreateWorkOrder Method :Ensures a new "Work Order" is created when status changes to Hired.
*/
    @IsTest
    static void testCreateWorkOrder_Success() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Interview__c interview = [
            SELECT Id, Candidate__c, Job_Position__r.Project__c, Job_Position__r.Job_Title__c 
            FROM Interview__c LIMIT 1
        ];
        
        System.runAs(u) {
            Test.startTest();
            interview.Interview_Status__c = RecruitmentApp_Constants.INTERVIEW_STATUS_HIRED;
            interview.Feedback__c = 'Hired for the project role.';
            update interview;
            Test.stopTest();
        }
        
        List<Work_Order__c> workOrders = [
            SELECT Candidate__c, Project__c, Status__c, Role_on_Project__c
            FROM Work_Order__c
            WHERE Candidate__c = :interview.Candidate__c
        ];
        
        System.assertEquals(1, workOrders.size(), 'One work order should be created upon hiring.');
        System.assertEquals(
            RecruitmentApp_Constants.WORKORDER_STATUS_NEW, 
            workOrders[0].Status__c, 
            'Work Order status should be New.'
        );
    }
    
    /*
* @description : test CreateWorkOrder Method :Ensures no Work Order is created when status changes to other values except "Hired".
*/
    @IsTest
    static void testCreateWorkOrder_NoWorkOrder() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        Interview__c interview = [
            SELECT Id, Candidate__c, Job_Position__r.Project__c, Job_Position__r.Job_Title__c 
            FROM Interview__c LIMIT 1
        ];
        
        System.runAs(u) {
            Test.startTest();
            interview.Interview_Status__c = RecruitmentApp_Constants.INTERVIEW_STATUS_OFFERED;
            interview.Feedback__c = 'Offered for the project role.';
            update interview;
            Test.stopTest();
        }
        List<Work_Order__c> workOrders = [
            SELECT Candidate__c, Project__c, Status__c, Role_on_Project__c
            FROM Work_Order__c
            WHERE Candidate__c = :interview.Candidate__c
        ];
        
        System.assertEquals(0, workOrders.size(), 'No work order should be created upon offering.');        
    }
    
    /*
* @description : test EventUpdated Method : Ensures that when Interview is updated, 
*               the related Event record’s StartDateTime, EndDateTime, and Location 
*               are updated accordingly.
*/
    
    
    @IsTest
    static void testEventUpdated() {
        Interview__c interview = [SELECT Id, Candidate__c, Job_Position__c, Interview_Date__c, Interview_Mode__c FROM Interview__c LIMIT 1];
        System.debug('interview'+interview);
        
        
        
        Test.startTest();
        
        DateTime newDate = interview.Interview_Date__c != null ? interview.Interview_Date__c.addDays(2) : DateTime.now().addDays(2);
        interview.Interview_Date__c = newDate;
        System.debug('newDate12'+interview.Interview_Date__c);
        interview.Interview_Mode__c = 'Online';
        update interview;
        Event updated = [SELECT Id, Candidate__c,StartDateTime, EndDateTime, Location  FROM Event WHERE Candidate__c = :interview.Candidate__c];
        Test.stopTest();
        
        
        System.assertEquals(newDate, updated.StartDateTime, 'Event StartDateTime should be updated');
        System.assertEquals(newDate.addHours(1), updated.EndDateTime, 'Event EndDateTime should be updated');
        System.assertEquals('Online', updated.Location, 'Event Location should be updated');
    }
    


    @IsTest
    static void testInterviewConflictCoverage() {
        
        Interview__c existingInterview = [
            SELECT Id,
            Candidate__c,
            Job_Position__c,
            Job_Position__r.Client__r.Id,
            Job_Position__r.Project__r.Id
            FROM Interview__c
            LIMIT 1
        ];
        
      
        Job_Position__c anotherJob = Recruitment_TestDataFactory.createJobPosition(
            existingInterview.Job_Position__r.Client__r,
            existingInterview.Job_Position__r.Project__r
        );
        insert anotherJob;
        
        
        DateTime startDT = DateTime.now().addDays(1).addHours(10);
        DateTime endDT = startDT.addHours(1);
        Event conflictingEvent = new Event(
            WhatId = anotherJob.Id,
            Candidate__c = existingInterview.Candidate__c,
            Subject = 'Conflicting Interview',
            StartDateTime = startDT,
            EndDateTime = endDT
        );
        insert conflictingEvent;
        
        
        existingInterview.Interview_Date__c = startDT;
        
        Test.startTest();
        try {
            update existingInterview;
        } catch (Exception e) {
            System.debug('Expected conflict caught: ' + e.getMessage());
        }
        Test.stopTest();
    }
    


    
}