force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the candidate being interviewed. Used to associate the interview with a specific candidate profile.</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>The scheduled or completed date and time of the interview. Important for planning and status tracking.</description>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job_Position__c.field-meta.xml
<CustomField>
    <fullName>Job_Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the open position or job role the interview is for. Helps identify the context of the interview.</description>
    <label>Job Position</label>
    <referenceTo>Job_Position__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup field referencing the client or company that is hiring for the position.</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected client should have the Status as Active</errorMessage>
        <filterItems>
            <field>Client__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Client object, linking the project to the company it is being executed for.</description>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewCleanupAndReminderBatchTest.cls
@IsTest
private class InterviewCleanupAndReminderBatchTest {
    
    @testSetup
    static void setupData() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        
        User u = new User(
            FirstName = 'Test',
            LastName = 'Owner',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser' + System.currentTimeMillis() + '@example.com',
            CommunityNickname = 'testuser' + System.currentTimeMillis(),
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_IN',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive=true
        );
        insert u;
        Group queue = new Group(Name = 'Interview Queue', Type = 'Queue');
        insert queue;
        GroupMember gm = new GroupMember(GroupId = queue.Id, UserOrGroupId = u.Id);
        insert gm;
        QueuesObject testQueue = new QueueSObject(QueueID = queue.id, SobjectType = 'Interview__c');
        insert testQueue;
        System.runAs(u) {
            
            Client__c client = Recruitment_TestDataFactory.createClient('Test Client', 'client@example.com');
            Project__c project = Recruitment_TestDataFactory.createProject('Test Project');
            Candidate__c cand1 = Recruitment_TestDataFactory.createCandidate('Candidate 1', 'candidate1@example.com');
            Candidate__c cand2 = Recruitment_TestDataFactory.createCandidate('Candidate 2', 'candidate2@example.com');
            insert new List<SObject>{ client, project, cand1, cand2 };
                
                Job_Position__c job = Recruitment_TestDataFactory.createJobPosition(client, project);
            insert job;
            
            Interview__c recentInterview = Recruitment_TestDataFactory.createInterview(cand1, job);
            recentInterview.OwnerId = u.Id; // owned by user
            recentInterview.Interview_Date__c = System.now().addDays(1);
            insert recentInterview;
            Test.setCreatedDate(recentInterview.Id, System.now().addMonths(-4));
            Interview__c oldInterviewQueue = Recruitment_TestDataFactory.createInterview(cand2, job);
            
            insert oldInterviewQueue;
            Test.setCreatedDate(oldInterviewQueue.Id, System.now().addMonths(-4));
            oldInterviewQueue.OwnerId = queue.id; // owned by queue
            update oldInterviewQueue;
        }
    }
     /**
     * @description Tests the schedulable execution of InterviewCleanupAndReminderBatch.
     *              Verifies that the class can be scheduled successfully using a CRON expression.
     *              This ensures that the Schedulable interface and execute(SchedulableContext) 
     *              method are properly implemented and covered.
     */
    @IsTest
    static void testSchedulableExecution() {
        Test.startTest();
        String cronExp = '0 0 0 ? * MON';
        System.schedule('Test Interview Cleanup Job', cronExp, new InterviewCleanupAndReminderBatch());
        Test.stopTest();
        System.assert(true, 'Schedulable execute method covered successfully.');   
    }
}